apps:
  namespace: prd
  image: ghcr.io/phurits/oqp-mgmt-frontend
  tag: prd
  replicas: 1
  imagePullSecrets: ghcr-registry
  port: 5173
  targetPort: 5173
ingress:
  host: inquesto.online
  path: /
  serviceType: ClusterIP
  tlsSecretName: tls-mgmt-frontend-prd
extraEnv:
  secretName: oqp-mgmt-frontend-env