apiVersion: v1
description: Online Quiz Platform Helm Chart (MGMT FRONTEND)
name: oqp-mgmt-frontend
version: 1.0.0
appVersion: 1.0.0
home: "https://inquesto.livequizplatform.online/"
maintainers:
  - name: Phurit Sararattnakaul
    email: 63010769@kmitl.ac.th
sources:
  - https://github.com/Live-Quiz-Project
